interface UserAgent {
  // The original user agent string.
  readonly source: string,
  readonly deviceType: string | null,
  readonly deviceVendor: string | null,
  readonly os: string,
  readonly osVersion: number | null,
  readonly browser: string,
  readonly browserVersion: number | null,
  readonly engine: string,
  readonly engineVersion: number | null,
  readonly isIphone: boolean,
  readonly isIpad: boolean,
  readonly isMobile: boolean,
  readonly isTablet: boolean,
  readonly isDesktop: boolean,
  readonly isBot: boolean,
  readonly isChrome: boolean,
  readonly isFirefox: boolean,
  readonly isSafari: boolean,
  readonly isIE: boolean,
  readonly isEdge: boolean,
  readonly isOpera: boolean,
  readonly isMac: boolean,
  readonly isChromeOS: boolean,
  readonly isWindows: boolean,
  readonly isIos: boolean,
  readonly isAndroid: boolean,
}
